### ISSUE TITLE
VS Marketplace doesn't have proper version

### ISSUE THREAD

**Issue by reed-jones** [calebporzio/simple-php-cs-fixer#10]
VS Marketplace seems to have v0.1.7 where as this repo has v0.1.6. 

0.1.7 doesn't seem to work for me, and this option `"simple-php-cs-fixer.usingCache": false` is missing, however cloning the repo and building from source works great

**Comment by jnbn** [comment]
Seems like this is solved.

**Comment by reed-jones** [comment]
Awesome, it does :+1:
