### ISSUE TITLE
php-cs-fixer ^3.0 compatibility issue

### ISSUE THREAD

**Issue by lucasvscn** [calebporzio/simple-php-cs-fixer#20]
Stop working after upgrade to version 3.0 of php-cs-fixer.

I've changed the config file to the new ".php_cs.dist.php" but, It keeps throwing "Unknown Error".

I tried to debug but my knowledge of VSCode extensions and NodeJS is limited
Only thing I know is that execution returns Error Code "255", but couldn't be able to know why.

When I've downgraded to ^2.19 version of php-cs-fixer everything back to work again.

Appreciate any help.

**Comment by PHLAK** [comment]
I'd love to see this addressed as well since this is a great and simple extension that "just works" normally.

Here's the [v3 upgrade guide](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.0/UPGRADE-v3.md) for reference.

**Comment by PHLAK** [comment]
I forked this repo, applied my PRs (#22 & #23) to fix this and published it to the extension marketplace as [Simple PHP CS Fixer 3](https://marketplace.visualstudio.com/items?itemName=PHLAK.simple-php-cs-fixer-3&ssr=false#overview).

**Comment by lucasvscn** [comment]
@PHLAK now it's working. thank you!
