### ISSUE TITLE
Can't find config file

### ISSUE THREAD

**Issue by imbakar** [calebporzio/simple-php-cs-fixer#5]
Hi,
I am facing the below problem !
**`Simple PHP CS Fixer: Can't find config file: [.php_cs.dist]`**

**Comment by lambal** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer
----
find in the source

**Comment by marvinhosea** [comment]
This does not help

**Comment by austenc** [comment]
Hey @calebporzio what would you think about using a default config file as a fallback? Happy to submit a PR if that sounds good. Thanks :)

**Comment by calebporzio** [comment]
Sounds good to me - would love to get this package working again (I could personally use it), just haven't had the time.

**Comment by austenc** [comment]
Thoughts on the default? Perhaps matching the one from Laravel Shift?

**Edit: Looks like this one is somewhat current**
https://gist.github.com/laravel-shift/cab527923ed2a109dda047b97d53c200

**Comment by calebporzio** [comment]
Thanks @austenc 

This extension now uses Laravel Shift's default .php_cs.dist file.
