### ISSUE TITLE
.php_cs.dist and change align result... Need Help

### ISSUE THREAD

**Issue by GrCOTE7** [calebporzio/simple-php-cs-fixer#8]
Hi, Calebporzio,

Very great plugin for VSCode !

Easy to run well directly, even when autosave function of VSCode activated !  Excellent !!!

But, I need help just for 1 thing: I like the unused lines are sautomatically removed and like my var are aligned

So, I put this file: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.13/.php_cs.dist

And globally very great result, again with auto-save feature :-) !

But, my alignment

```
                'pari' => [
                    'label'   => 'Sortie',
                    'tab'     => 'Paris',
                    'type'    => 'dropdown',
                    'options' => ['Pile', 'Face'],
                ]
```
become
```
                'pari' => [
                    'label' => 'Sortie',
                    'tab' => 'Paris',
                    'type' => 'dropdown',
                    'options' => ['Pile', 'Face'],
                ]
```

Of course, I 've look the README and saw this part:

> binary_operator_spaces [@Symfony]

>Binary operators should be surrounded by space as configured.
>Configuration options:
>align_double_arrow (false, null, true): whether to apply, remove or ignore double arrows alignment; >defaults to false. DEPRECATED: use options operators and default instead
>align_equals (false, null, true): whether to apply, remove or ignore equals alignment; defaults to false. >DEPRECATED: use options operators and default instead
>default ('align', 'align_single_space', 'align_single_space_minimal', 'no_space', 'single_space', null): >default fix strategy; defaults to 'single_space'
>operators (array): dictionary of binary operator => fix strategy values that differ from the default >strategy; defaults to []

But I'm lost, and don't know what and where put what for a param to remove this non-alignment...

Can you help me about that ?

**Comment by GrCOTE7** [comment]
Hey, Re !

Sorry if you read all, but, I find the answer for resolve that:

If that can help others:

```
        // Custom C57.fr 's rule
        'array_syntax' => ['syntax' => 'short'],
                'binary_operator_spaces'  => [
            'default'   => 'single_space',
            'operators' => [
               '=' => 'align_single_space_minimal',
               '=>' => 'align_single_space_minimal',
           ]
        ],
```

Go on to progamm such script, Calebporzio ! You' ll reach sun :-) !

**Comment by calebporzio** [comment]
Great, glad you resolved it!
